### ISSUE TITLE
Exercise7/Solution2:deployHandler() fails to monitor/redeploy AnotherVerticle

### ISSUE THREAD

**Issue by neilr8133** [InfoSec812/vertx-by-example#1]
The method `Exercise7/Solution2.groovy:deployHandler()` is hard-coded to be the handler for `EventVerticle`, but is also invoked for `AnotherVerticle`.  So log messages and attempts to re-launch the verticle will all refer to `EventVerticle`, not `AnotherVerticle`.

**Comment by neilr8133** [comment]
Probably-related:

```
$ vertx run Solution2.groovy
Succeeded in deploying verticle
Successfully deployed EventVerticle
Failed to deploy EventVerticle
io.vertx.core.impl.NoStackTraceThrowable: Random deployment failure of EventVerticle

Failed to deploy EventVerticle
io.vertx.core.impl.NoStackTraceThrowable: Random deployment failure of EventVerticle

Failed to deploy EventVerticle
io.vertx.core.impl.NoStackTraceThrowable: Random deployment failure of EventVerticle

Unhandled exception
java.lang.IllegalStateException: Result is already complete: succeeded
        at io.vertx.core.impl.FutureImpl.checkComplete(FutureImpl.java:164)
        at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:108)
        at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:135)
        at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:23)
        at io.vertx.core.eventbus.impl.EventBusImpl.lambda$callCompletionHandlerAsync$2(EventBusImpl.java:340)
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:316)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:440)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by InfoSec812** [comment]
Yep. I hadn't completely generalized that bit. Thanks for the feedback!

Deven
